### ISSUE TITLE
Pixel C Oreo update

### ISSUE THREAD

**Issue by steve-j-wilcox** [nmilosev/termux-fedora#12]
After updating to Oreo I get

startfedora
/usr/libexec/grepconf.sh: line 3: 32574 Bad system call         (core dumped) grep -qsi "^COLOR.*none" /etc/GREP_COLORS
/usr/libexec/grepconf.sh: line 3: 32586 Bad system call         (core dumped) grep -qsi "^COLOR.*none" /etc/GREP_COLORS

When trying to run fedora. Any ideas?

**Comment by steve-j-wilcox** [comment]
This is on a Pixel C

**Comment by steve-j-wilcox** [comment]
The install runs fine, and the installation seems to be present and correct. It is running the startfedora script that generates the error and similar errors occur with termux-ubuntu, which would seem to imply that there is an issue with proot and Android 8.0.

**Comment by steve-j-wilcox** [comment]
After a reinstall of termux and fedora the error is now;

All done! Start Fedora with 'startfedora'. Gets update with regular 'dnf update'.
$ start
start-stop-daemon  startfedora
$ startfedora
proot error: execve("/usr/bin/env"): No such file or directory
proot info: possible causes:
  * the program is a script but its interpreter (eg. /bin/sh) was not found;
  * the program is an ELF but its interpreter (eg. ld-linux.so) was not found;
  * the program is a foreign binary but qemu was not specified;
  * qemu does not work correctly (if specified);
  * the loader was not found or doesn't work.
fatal error: see `proot --help`.
proot error: can't chmod '/data/data/com.termux/files/usr/tmp//proot-14412-k8tRX2': No such file or directory
proot error: can't chdir to '
                             ': No such file or directory

**Comment by nmilosev** [comment]
This is very similar to #18 which leads me to believe that this is related either to proot or Pixel C or Android Oreo. :(

Maybe we can try to ping guys at proot or @termux author to see if they know something?

**Comment by steve-j-wilcox** [comment]
OK will raise with them. It does seem to be proot issue as all worked well prior to the Oreo update

**Comment by darkoverlordofdata** [comment]
FYI - I tried both the termux-ubuntu and termux-fedora scripts on 3 devices:
nexus 4 running android 5.1
firehd 10 2017 
asus zenbook running android-x86 6.0 r3

All get the same error as above:
proot error: execve("/usr/bin/env"): No such file or directory

You might consider that this is a broader issue.

**Comment by nmilosev** [comment]
You would have to modify the script for it to run on x86. It wouldn't be that difficult, you just have to find the appropriate docker image or make a rootfs yourself.

`proot error: execve("/usr/bin/env"): No such file or directory` is related to architecture it seems even though it is a bit obscure.

If you need help with setting everything up for x86 let me know.

**Comment by srdegraaf** [comment]
You might be  interested in this:
https://github.com/termux/proot/issues/9
The fix for the proot error is to add
unset LD_PRELOAD
at the beginning of the startfedora script

**Comment by nmilosev** [comment]
Finally fixed! Thanks everyone for help.
