### ISSUE TITLE
how connect lxde from remote?

### ISSUE THREAD

**Issue by wangmu0579** [nmilosev/termux-fedora#16]
I met a new problem and not found a solution after google.
Now I installed the @lxde and get GUI from XSDL Xserver in Android phone.

Do we have way connect lxde from the remote computer? Think about take a small computer is very cool.
I tried install the xrdp server in Fedora and using Windows RDP client. But I blocked at input the user/password.
Will try to google the openBox.

**Comment by nmilosev** [comment]
Duplicate of #15
