### ISSUE TITLE
boot loop

### ISSUE THREAD

**Issue by kurokirasama** [nmilosev/termux-fedora#19]
Hello, 

after finishing executing the script, i got into boot loop.... what can i do?
Hard reboot allow me to enter my phone again, then i uninstall termux, but still got bottloop

**Comment by nmilosev** [comment]
Not really sure what you mean, without more information.

Your phone actually got into bootloop? Or the chroot?

**Comment by kurokirasama** [comment]
yeah, an actual bootloop. I fixed it by deleting termux folder on /data/data/ via twrp...

**Comment by nmilosev** [comment]
Wow, okay that's weird. It's possible that because you are rooted, something really bad happened and termux tried to access some files it should not. Please run termux without root when using termux-fedora if possible.

Thanks for your report!
