### ISSUE TITLE
Installing some packages fails inside fedora chroot

### ISSUE THREAD

**Issue by xsacha** [nmilosev/termux-fedora#2]
> Upgrading   : tzdata-2016j-1.fc25.noarch        1/6 Error unpacking rpm package tzdata-2016j-1.fc25.noarchError unpacking rpm package tzdata-2016j-1.fc25.noarch
> error: unpacking of archive failed on file /usr/share/zoneinfo/Africa/Bamako;587eab7c: cpio: link             Upgrading   : e2fsprogs-1.43.3-1.fc25.aarch64   2/6
> Error unpacking rpm package e2fsprogs-1.43.3-1.fc25.aarch64
> Error unpacking rpm package e2fsprogs-1.43.3-1.fc25.aarch64                                                 error: tzdata-2016j-1.fc25.noarch: install failed     error: unpacking of archive failed on file /usr/sbin/fsck.ext2;587eab7c: cpio: link                           Upgrading   : coreutils-common-8.25-15.fc25.a   3/6 Error unpacking rpm package coreutils-common-8.25-15.fc25.aarch64                                           Error unpacking rpm package coreutils-common-8.25-15.fc25.aarch64                                           error: e2fsprogs-1.43.3-1.fc25.aarch64: install failed
> error: unpacking of archive failed on file /usr/share/locale/af/LC_TIME/coreutils.mo;587eab7c: cpio: link
> 

Not sure what is causing the errors but it looks like it is failing when overwriting the old existing files?

**Comment by nmilosev** [comment]
Uh, there is some issues with soft links in chroot's. I'm not sure how to fix it.

**Comment by xsacha** [comment]
This makes installing/updating software extremely difficult. Bit of a blocker.

**Comment by nmilosev** [comment]
Just realized which repo this is.

Could you try this as an alternative?

https://github.com/nmilosev/anyfed 

It's a bit fresher, and it has link2symlink included. It is supposed to be a successor to this project. Forgot to mention it in the README. Sorry!

**Comment by nmilosev** [comment]
Just updated this as well. So please try reinstalling and let me know if it's better.

**Comment by nmilosev** [comment]
Running a `dnf update` on a fresh new installation works fine for me now. Please let me know if this fixes your problem as well. And thanks for reporting.

**Comment by xsacha** [comment]
Thanks. I'll switch to anyfed if it is the successor.

**Comment by nmilosev** [comment]
Both should work the same now. :)

**Comment by xsacha** [comment]
First run, dnf update gives:
gpgme.GpgmeError: (7, 121, 'Unsupported protocol')

**Comment by nmilosev** [comment]
Please try fully cleaning up and reinstalling. Sorry

**Comment by xsacha** [comment]
This was a clean termux. Did something change recently?

**Comment by xsacha** [comment]
Also anyfed is still on f24 and I didnt know architecture name forr armv8

**Comment by xsacha** [comment]
Fixed the issue by running dnf update inside termux-chroot so that gnupg could install.

**Comment by nmilosev** [comment]
Can you provide the exact steps please? :) If someone else has an issue
like this.

**Comment by xsacha** [comment]
I tried installing gnupg in termux first and also in fedora pip3.5 but not sure that diid anything. It failed in fedora.

Otherwise just cloned repo, ran script, termux-chroot, startfedora, dnf update.

After this two packages failed: e2fsprogs and glibc. Both due to linking errors as before.

error: glibc-2.24-4.fc25.aarch64: install failed
error: unpacking of archive failed on file /usr/sbin/fsck.ext2;589b8087: cpio: link
e2fsprogs-1.43.3-1.fc25.aarch64 was supposed to be installed but is not!

**Comment by xsacha** [comment]
Another thing I noticed is termux-chroot makes all disk operations take roughly 4 times longer! Avoid!
I only go in to it for things that require that directory structure.
