### ISSUE TITLE
termuxfedora crashes

### ISSUE THREAD

**Issue by JOKERHACK** [nmilosev/termux-fedora#23]
i have success fully installed fedora in termux all was going well.but after i updated it end with some errors and crashed.now when i type any command it shows{bash: /bin/dnf:user/bin/python3:bad interpreter:permission denied} does any one know how to fix this???????

**Comment by JOKERHACK** [comment]
hello any one

**Comment by nmilosev** [comment]
Hello, thank you for reporting this issue. 

I think you installed the wrong arch. What is the output of `dpkg --print-architecture` in Termux?

**Comment by nmilosev** [comment]
Closing this, not enough info.
