### ISSUE TITLE
Problem

### ISSUE THREAD

**Issue by chemostafa** [nmilosev/termux-fedora#25]
startfedora
proot error: '/bin/env' not found (root = /data/data/com.termux/files/home/fedora, cwd = /data/data/com.termux/files/home, $PATH=(null))
fatal error: see `proot --help`.

**Comment by chemostafa** [comment]
Solved : and sorry I poor in English 👀
Delete any think you download about fedora , you can't uninstall fedora coz you install it with problem , so I do clear termux data from the phone sitting , and start from the first 👀
Apt update and pkg update  and the necessary things you use..
The first thing you do is know if you are 64 or 32 with this  :
dpkg --print-architecture
If you 32 only  show (arm) and if u 64 it will show the number 
Print this link and press enter 

apt update && apt install wget -y && /data/data/com.termux/files/usr/bin/wget https://raw.githubusercontent.com/nmilosev/termux-fedora/master/termux-fedora.sh

sh termux-fedora.sh
End link and also you will find it in this webpage ((https://github.com/nmilosev/termux-fedora/blob/master/README.md )) 
So next setup do ls you will see thetermux-fedora.sh and the color will be white and this setup important do this 
Chmod +x termux-fedora.sh
No it Green color 
Last setup 
do this if you 64
 sh termux-fedora.sh f27_arm64
Or do this if you 32 and it will just show only arm remember? 
sh termux-fedora.sh f27_arm 
After download
Do this
startfedora
It will work in shaa Allah 👍
If you are 64 and you download 32 don't dawnlod 64 on it , just clear termux data from phone sitting and start from Bingen coz like I say it will not uninstall coz it install with wrong way 
Sorry for my English 👀

**Comment by nmilosev** [comment]
Thank you for your report!

Glad you got it working.
