### ISSUE TITLE
proot info: vpid 1: terminated with signal 11

### ISSUE THREAD

**Issue by PotcFdk** [nmilosev/termux-fedora#4]
When I run the script, it exits correctly and tells me about `startfedora`. Running `startfedora` leads to the error output above.
Device: OnePlus 3T, OxygenOS 3.5.4 (Android 6.0.1), Termux installed via F-Droid

**Comment by nmilosev** [comment]
I'm pretty sure this is ARM64 device. Are you sure you installed the correct image?

**Comment by PotcFdk** [comment]
I'm pretty sure I did. I will test it one more time and report back soon.

**Comment by Pant** [comment]
Same here with Samsung S5 Lineageos. Termix installed from fdroid.

**Comment by PotcFdk** [comment]
It worked when I tried it a few minutes ago. I don't know what was happening before, maybe the previously downloaded fedora.tar.xz had been corrupted. I'll hand over this issue to @Pant - see if you can figure out what's up with him.

**Comment by Neo-Oli** [comment]
@PotcFdk Perhaps you updated proot? There was an update last night that should fix some of the problems on certain kernels.

**Comment by Pant** [comment]
With regard me, I tried it yesterday (when I posted) and the proot package since then is in the same version (5.1.102).

**Comment by xsacha** [comment]
I have started getting this issue as well today.

**Comment by nmilosev** [comment]
This should be fixed with the latest proot and images.
