### ISSUE TITLE
gpgme.GpgmeError, unsupported protocol

### ISSUE THREAD

**Issue by zhangew** [nmilosev/termux-fedora#5]
Dear Nmilosev,

I've installed the fedora according to your instruction successfully.
And when I started it with 'startfedora', and I'd like to install some softwares.

I encountered the problem which is like this:
"warning: /var/cache/dnf/updates-e042e478e0621ea6/packages/mariadb-10.0.27-1.fc23.x86_64.rpm: Header V3 RSA/SHA256 Signature, key ID 34ec9cba: NOKEY
The downloaded packages were saved in cache until the next successful transaction."
......
gpgme.GpgmeError: (7, 121, 'Unsupported protocol')

How should I proceed?

Any help would be appreciated.

best regards.

**Comment by zhangew** [comment]
I solved it by adding an option after the dnf install command: --nogpgcheck.

**Comment by nmilosev** [comment]
You can use `--nogpgcheck` for now, what is very weird: `fc23`? That is Fedora 23.

I will look into it.

**Comment by nmilosev** [comment]
Can't reproduce. :(

This is a stupid question: Is your date on your device correctly setup?

**Comment by xsacha** [comment]
I have always got this same issue on termux-fedora/anyfed.
Date is set fine.

**Comment by xsacha** [comment]
I think I fixed it by installing gnupg in termux
