### ISSUE TITLE
Postgresql failed to connect to bus: no such file or directory

### ISSUE THREAD

**Issue by Lexiie** [nmilosev/termux-fedora#8]
how I can fix that

**Comment by nmilosev** [comment]
Difficult to say maybe it needs dbus to run? We don't have things like dbus or systemd running, so you have to investigate if it is possible to run postgres manually.

**Comment by L-jasmine** [comment]
if someone (like me) not install wget,Termux will find a wget,but it isn't /data/data/com.termux/files/usr/bin/wget.This wget can't connect that web whose use https.
so I think this sh need add a 'pkg install wget'.(my english is poor,sry)
